# .aikido.yml

# .aikido.yml
# Vynutíme skenování testovacích souborů
scan_test_details: true

paths:
  include:
    - "src/main/java/org/owasp/benchmark/testcode/**"
  exclude:
    - "src/main/resources/**"
    - "src/main/webapp/**"
    - "helpers/**"
    - "scripts/**"
    - "doc/**"
